### ISSUE TITLE
Could you provide a command line script please?

### ISSUE THREAD

**Issue by Naereen** [wyounas/homer#4]
Hi!
Your tool looks very interesting, but it is quite tedious to have to write a Python script in order to test it.
Could you maybe try to write a command line script, that takes a file and runs the homer analyses on it?
I can test it when a prototype will be ready, if you need some help :)
Thanks in advance!

**Comment by wyounas** [comment]
Hello @Naereen, thank you so much for the message.

Yes, I am working on it. Will likely push a simple command-line utility this weekend. Will ping you once it's in the repo.

Thanks.

**Comment by Naereen** [comment]
@wyounas awesome!

**Comment by wyounas** [comment]
Hey @Naereen, 

I just released a command-line utility. More details here: https://github.com/wyounas/homer#command-line.

To run:
> python homer_cmd.py --name article_name --author lalala --file_path=/correct/path/to/file.txt

(where `article_name` and `author` are optional, and `file_path` is mandatory).

If you can test this, that will be super helpful. Let me know if it looks good, and I will then close the issue :)

Thanks so much!

**Comment by wyounas** [comment]
Closing this as this has been done and released :)
